---
title: "DAISIErobustness vignette"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{DAISIErobustness vignette}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## Introduction

### What is DAISIErobustness?
DAISIErobustness is an R package for testing of the robustness of the island biogeography model "[DAISIE](https://github.com/rsetienne/DAISIE)" (_Dynamical Assembly of Islands by Speciation, Immigration and Extinction_)  to more complex and potentially more realistic evolutionary models. Different measures of error of number of species, endemics, non-endemics and evolutionary trajectories are used to determine whether the alternative models can influence the inference capabilities of the current DAISIE model.

### DAISIErobustness pipeline
DAISIErobustness consists of a pipeline designed to measure the error one creates when extending the standard DAISIE model with new features. Examples of such new additions include the modelling of island ontogeny, as per the General Dynamic Model<sup>1</sup>, sea level changes<sup>2</sup>, and non-oceanic scenarios. The error measure is obtained by simulating and comparing DAISIE data using simulation code that builds upon the existing DAISIE simulations by including geodynamic processes.

## Usage
### Running the pipeline
The full pipeline can be called by the external function `run_robustness()`. If the `save_output` argument is set to `TRUE`, a folder named results will be created in the current working directory, into which a folder named after the selected parameter space with an `.RData` file will be saved. This `.RData` file will contain the results for all the replicates of a given parameter set. If `save_output` is set to `FALSE`, the results object will be returned and not saved to a file.
```{r eval = FALSE, run_robustness}
library(DAISIErobustness)
run_robustness(
  param_space_name = "nonoceanic",
  param_set = 1,
  replicates = 2,
  distance_method = "abs",
  save_output = FALSE
)
```

### RNG concencerns when batching jobs
While this package can run locally without issues, it was designed primarily to run in batch jobs on HPCCs, in particular the University of Groningen Peregrine HPCC. For this purpose, and assuming a user has access to the Peregrine Cluster, there are pre-prepared submission bash scripts in the `bash/` folder. However, care should be taken when running this package (through the `run_robustness()` function) in a distributed computing setting. The RNG algorithm used (Mersenne-Twister) is seeded within each run by a combination of the system time and the index of the current parameter set. For this reason, if jobs for multiple parameter spaces (which will always share parameter set indices) are started simultaneously, **said jobs WILL be running with the same seed**! To prevent this, make sure all jobs from a given parameter space have started (and are not on queue) before submitting the next parameter space.

## References
<sup>1</sup>Whittaker, Robert J., Kostas A. Triantis, and Richard J. Ladle. "A general dynamic theory of oceanic island biogeography." _Journal of Biogeography_ 35.6 (2008): 977-994.

<sup>2</sup>Fernández‐Palacios, José María, et al. "Towards a glacial‐sensitive model of island biogeography." _Global Ecology and Biogeography_ 25.7 (2016): 817-830.
