---
title: "DAISIErobustness diagnostics"
output:
  html_document:
    df_print: paged
---


Notes on parameter spaces failing
```{r}
out <- DAISIErobustness::get_runtime_params(logs_folder_path = "tests/testthat/testdata/logs")

names <- unique(out$param_space_name)
names <- names[!grepl("corrupted_", names)]
status <- unique(out$status)
status

resultless_list <- list()
failed_list <- list()
timeout_list <- list()
success_ratio <- data.frame(
  "param_space" = character(),
  "sucess_rate" = numeric(),
  "failed_rate" = numeric(),
  "timeout_rate" = numeric()
)
for (i in seq_along(names)) {
  space_length <- nrow(DAISIErobustness::load_param_space(names[i]))

  resultless_list[[i]] <- dplyr::filter(
    out,
    param_space_name == names[i],
    status != "COMPLETED" & status != "RUNNING"
  )
  failed_list[[i]] <- dplyr::filter(
    out,
    param_space_name == names[i],
    status == "FAILED"
  )
  timeout_list[[i]] <- dplyr::filter(
    out,
    param_space_name == names[i],
    status != "COMPLETED" & status != "RUNNING" & status != "FAILED"
  )
  success_ratio[i, 1] <- names[i]
  success_ratio[i, 2] <- (space_length - nrow(resultless_list[[i]])) /
    space_length
  success_ratio[i, 3] <- nrow(failed_list[[i]]) / space_length
  success_ratio[i, 4] <- nrow(timeout_list[[i]]) / space_length
}

names(resultless_list) <- names
names(failed_list) <- names
names(timeout_list) <- names
resultless_list
failed_list
timeout_list
```

Proportion of successful runs in pilot
```{r}
ggplot2::ggplot(data = success_ratio, ggplot2::aes(param_space, sucess_rate)) +
  ggplot2::geom_col() +
  ggplot2::theme_classic() +
  ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 25))
```
 
Proportion of failed (errors in ML mostly)
 
```{r}
ggplot2::ggplot(data = success_ratio, ggplot2::aes(param_space, failed_rate)) +
  ggplot2::geom_col() +
  ggplot2::theme_classic() +
  ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 25))
```

Proportion of timeouts

```{r}
ggplot2::ggplot(data = success_ratio, ggplot2::aes(param_space, timeout_rate)) +
  ggplot2::geom_col() +
  ggplot2::theme_classic() +
  ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 25))
```

Of the timeouts, how many single novel_sim runs per replicate, and how many fail hang from the begining?

```{r}
ran_novel_sim_list <- list()
never_finish_list <- list()
for (i in seq_along(timeout_list)) {
  paths <- file.path("D:/code/DAISIErobustness/robustness_pilot/logs", timeout_list[[i]]$log_name)
  ran_sim <- c()
  for (j in seq_along(paths)) {
    log_lines <- readLines(con = paths[j], n = 2000)
    ran_sim[j] <- sum(grepl("novel_ml:", log_lines))
  }
  ran_novel_sim_list[[i]] <- ran_sim
  never_finish <- sum(ran_sim == 0)
  never_finish_list[[i]] <- never_finish
}
names(ran_novel_sim_list) <- names(timeout_list)
names(never_finish_list) <- names(timeout_list)
```
How many novel_sims ran in job
```{r}
ran_novel_sim_list
```

How many never ran a single novel sim
```{r}
never_finish_list
```
